### ISSUE TITLE
Error after deploying this app

### ISSUE THREAD

**Issue by prathmeshgat** [heroku/alpinehelloworld#3]
at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=thawing-gorge-37216.herokuapp.com request_id=9631a993-661e-4a93-809b-9a770cb9e161 fwd="96.247.27.140" dyno= connect= service= status=503 bytes= protocol=https

I followed this(https://devcenter.heroku.com/articles/container-registry-and-runtime) article and deployed this app I get the above error when I enter heroku open command in log tail. Please let me know proper way to deploy the app.

**Comment by dmathieu** [comment]
It looks like your web process isn't running. Have you tried starting it with `heroku ps:scale web=1`?
If this still doesn't work, could you open a support ticket at help.heroku.com? That will make it much easier for us to help you.
