### ISSUE TITLE
How do I run the tests?

### ISSUE THREAD

**Issue by klebba** [heroku/alpinehelloworld#7]
It's not clear to me how to run the test case

**Comment by dmathieu** [comment]
What test case are you talking about?
This repository is used in [this article](https://devcenter.heroku.com/articles/container-registry-and-runtime) to walk through our docker registry.

**Comment by klebba** [comment]
Yep -- I read the article. There's a note that reads `For testing purposes, we suggest that your Dockerfile or code read from the $PORT environment variable [...]`

This repository contains:
https://github.com/heroku/alpinehelloworld/blob/master/webapp/tests.py

Would appreciate more info about how to run the tests. Thanks!

**Comment by dmathieu** [comment]
I believe this unit test has been auto-generated.
The `for testing purposes` here means manual testing locally.
It's not unit tests, but because locally, you could use the `EXPOSE` argument, which our platform doesn't support.
