### ISSUE TITLE
environment variables?

### ISSUE THREAD

**Issue by ackvf** [heroku/alpinehelloworld#8]
Hello, is there a documentation for which env variables does heroku pass to the docker and to the app?

I need to access latest commit hash in the app.

**Comment by dmathieu** [comment]
We pass exactly the same environment variables to slugs and docker apps.
That means you can get access to the commit hash with the dyno-metadata feature: https://devcenter.heroku.com/articles/dyno-metadata

**Comment by ackvf** [comment]
Thank you for your answer, I did manage to get `HEROKU_` variables in the env, however, the `HEROKU_SLUG_COMMIT` is empty. I guess it is not unexpected since I did not build from git push, but as you can see, the commit seems to be available in the scope under `npm_package_gitHead`, therefore I would expect in `HEROKU_SLUG_COMMIT` as well. Are my thoughts correct?
[For reference.](https://github.com/getsentry/raven-ruby/issues/563)

**Comment by dmathieu** [comment]
This is because the `docker push` API doesn't allow us to provide any information such as a commit sha.
We cannot make the data available today unfortunately.
